//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WhriaView.rc
//
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WHRIAVIEW_DIALOG            102
#define IDS_CANNOT_START                102
#define IDS_TIP1                        102
#define IDS_STOPPED                     103
#define IDS_TIP2                        103
#define IDS_STRING163                   104
#define IDS_TIP3                        104
#define IDS_STRING164                   105
#define IDS_TIP4                        105
#define IDS_STRING165                   106
#define IDS_TIP5                        106
#define IDS_STRING166                   107
#define IDS_TIP6                        107
#define IDS_STRING167                   108
#define IDS_TIP7                        108
#define IDS_STRING168                   109
#define IDS_TIP8                        109
#define IDS_STRING169                   110
#define IDS_TIP9                        110
#define IDS_STRING170                   111
#define IDS_TIP10                       111
#define IDS_STRING171                   112
#define IDS_TIP11                       112
#define IDS_STRING172                   113
#define IDS_TIP12                       113
#define IDS_STRING173                   114
#define IDS_TIP13                       114
#define IDS_STRING174                   115
#define IDS_TIP14                       115
#define IDS_STRING175                   116
#define IDS_TIP15                       116
#define IDS_STRING176                   117
#define IDS_TIP16                       117
#define IDS_STRING177                   118
#define IDS_TIP17                       118
#define IDS_STRING178                   119
#define IDS_TIP18                       119
#define IDS_STRING179                   120
#define IDS_TIP19                       120
#define IDS_TIP20                       121
#define IDS_EXIT                        122
#define IDS_SERVERNONRESPONSE           123
#define IDS_NOREMOVEROOT                124
#define IDS_CONFIRM_DELETE              125
#define IDS_DOWN_SELECT_FOLDER          126
#define IDS_TOOLTIP1                    127
#define IDR_MAINFRAME                   128
#define IDS_TOOLTIP2                    128
#define IDD_DIALOG_LOGIN                129
#define IDS_TOOLTIP3                    129
#define IDD_DIALOG_PATIENT              130
#define IDB_CLOSED                      130
#define IDB_FIRST_TREE_ICON             130
#define IDD_DIALOG_SQLCONFIG            130
#define IDS_TOOLTIP4                    130
#define IDB_CLOSED_SEL                  131
#define IDD_DIALOG_CONFIGMANAGER        131
#define IDS_TOOLTIP5                    131
#define IDB_OPEN                        132
#define IDD_DIALOG_SELECTEDUSER         132
#define IDS_TOOLTIP6                    132
#define IDD_DIALOG_PICTURELIST          133
#define IDB_OPEN_SEL                    133
#define IDB_LAST_TREE_ICON              133
#define IDS_TOOLTIP7                    133
#define IDI_ICON_MAINDX                 134
#define IDS_FILE_NOTEXIST               134
#define IDI_ICON_SUBDX                  135
#define IDS_SHORT_KEYWORD               135
#define IDI_ICON_PRIV1                  136
#define IDD_DIALOG_CPLesion             136
#define IDS_RECEIVE_LIST                136
#define IDI_ICON_PRIV2                  137
#define IDS_UPLOAD_FOLDER               137
#define IDI_ICON_PRIV3                  138
#define IDS_NO_PHOTO_REPORT             138
#define IDI_ICON_PRIV4                  139
#define IDS_SELECT_FOLDER2              139
#define IDI_ICON_PRIV5                  140
#define IDS_SELECT_FOLDER3              140
#define IDI_ICON_PRIV6                  141
#define IDS_RENAME_FILE                 141
#define IDI_ICON_PRIV7                  142
#define IDS_START_BUILD_PPT             142
#define IDI_ICON_PRIV8                  143
#define IDS_FAIL_LOAD_PPT               143
#define IDD_DIALOG_IMAGEDISPLAY         144
#define IDI_ICON_PRIV9                  144
#define IDS_SELECT_FOLDER4              144
#define IDI_ICON_PRIV0                  145
#define IDS_EMPTY_FOLDER                145
#define IDI_ICON_PATHODX                146
#define IDS_MANY_FILE                   146
#define IDI_ICON_HISTORY                147
#define IDS_FAIL_CREATE_FOLDER          147
#define IDI_ICON_RED                    148
#define IDS_DRAG_FILE_NOT_FOLDER        148
#define IDB_BITMAP_INVALID              149
#define IDS_TOO_MANY_PHOTOS             149
#define IDS_ERROR_GET_INFO              150
#define IDD_CHOOSEDIR_DIALOG            151
#define IDD_DIALOG_CLIENTCONFIG         154
#define IDD_DIALOG_DXSELECTLIST         156
#define IDI_ICON_OPEN                   158
#define IDI_ICON_CLOSED                 159
#define IDB_BITMAP_CHECKMARK            162
#define IDD_DIALOG_CUSTOMDX             163
#define IDB_BITMAP1                     168
#define IDB_BITMAP_UPDATEON             168
#define IDR_MENU_POPUP_LIST             169
#define IDD_DIALOG_OPTION               171
#define IDR_MENU_POPUP_TREE             171
#define IDR_MENU_POPUP_TREE_UPLOAD      171
#define IDR_MENU_MAIN                   172
#define IDD_DIALOG_OPTION1              173
#define IDD_DIALOG_OPTION2              174
#define IDD_DIALOG_INPUT                176
#define IDD_DIALOG1                     177
#define IDD_DIALOG_PROGRESS             177
#define IDB_BITMAP_L1                   180
#define IDB_BITMAP_L3                   181
#define IDB_BITMAP_L2                   182
#define IDB_BITMAP_R1                   183
#define IDB_BITMAP_R3                   184
#define IDB_BITMAP_R2                   185
#define IDB_BITMAP_Z2                   186
#define IDB_BITMAP_Z1                   187
#define IDB_BITMAP_Z3                   188
#define IDD_DIALOG2                     189
#define IDD_DIALOG_SELECT_TYPE          189
#define IDD_DIALOG_DATAMANAGER          190
#define IDB_BITMAP_BLACK                191
#define IDB_BITMAP2                     193
#define IDB_BITMAP_LOGO                 193
#define IDD_DIALOG_LOGO                 194
#define IDD_DIALOG_VIEWLOGO             194
#define IDD_DIALOG3                     195
#define IDD_DIALOG_SELECTCHECK          196
#define IDB_BITMAP_N1                   197
#define IDB_BITMAP_N2                   198
#define IDB_BITMAP_N3                   199
#define IDB_BITMAP_P1                   200
#define IDB_BITMAP_P2                   201
#define IDB_BITMAP_P3                   202
#define IDB_BITMAP4                     204
#define IDB_BITMAP5                     205
#define IDB_BITMAP3                     206
#define IDB_BITMAP_RO3                  206
#define IDB_BITMAP_RO1                  207
#define IDB_BITMAP_RO2                  208
#define IDB_BITMAP_ROT3                 209
#define IDB_BITMAP_ROT1                 210
#define IDB_BITMAP_ROT2                 211
#define IDB_BITMAP_F12                  212
#define IDD_DIALOG_DATEPICKER           213
#define IDB_BITMAP_C1                   214
#define IDB_BITMAP_C                    214
#define IDC_EDIT_DERMASTAT_ID           1000
#define IDC_DIRECTORY_NAME              1000
#define IDC_EDIT_DERMASTAT_NAME         1001
#define IDC_DIRECTORY_TREE              1001
#define IDC_EDIT_DERMASTAT_SEX          1002
#define IDC_DRIVE_COMBO                 1002
#define IDC_BUTTON_AUTO                 1003
#define IDC_COMBO_LOGINID               1003
#define IDC_LIST_PICTURELIST            1004
#define IDC_EDIT_LOGINPASSWD            1004
#define IDC_BUTTON_LOGINOK              1005
#define IDC_EDIT_SQLPASSWD              1006
#define IDC_EDIT_SQLHOST                1007
#define IDC_EDIT_INPUT                  1008
#define IDC_EDIT_SQLDBNAME              1008
#define IDC_PROGRESS_STATUS             1011
#define IDC_BUTTON_NEWUSER              1012
#define IDC_EDIT_NEWUSERNAME            1013
#define IDC_COMBO_USERSELECTED_PRIV     1014
#define IDC_EDIT_USERSELECTED_ID        1015
#define IDC_STATIC_ABOUT                1016
#define IDC_EDIT_USERSELECTEDPASSWD1    1016
#define IDC_BUTTON_RELOAD               1017
#define IDC_EDIT_DERMASTAT_AGE          1018
#define IDC_BUTTON_STOP                 1018
#define IDC_CHECK_OPTION                1019
#define IDC_CHECK_SEARCH_FILENAME       1019
#define IDC_BUTTON_COMMENT              1020
#define IDC_EDIT1                       1021
#define IDC_EDIT_THUMBPATH              1021
#define IDC_EDIT_SERVERIP               1021
#define IDC_EDIT_DX                     1021
#define IDC_EDIT_DELAY1                 1021
#define IDC_EDIT_NEWUSER                1021
#define IDC_EDIT_INPUTBOX               1021
#define IDC_EDIT_SINGLE_DATA_FOLDER     1021
#define IDC_EDIT2                       1022
#define IDC_EDIT_ORGPATH                1022
#define IDC_EDIT_ID                     1022
#define IDC_EDIT_NAME                   1022
#define IDC_EDIT3                       1023
#define IDC_EDIT_SQLDB                  1023
#define IDC_EDIT_PASS                   1023
#define IDC_EDIT_ICD                    1023
#define IDC_EDIT4                       1024
#define IDC_EDIT_SQLPASS                1024
#define IDC_EDIT_IP                     1024
#define IDC_EDIT_INPUT_DIAGNOSIS        1024
#define IDC_EDIT_DLG_ID                 1024
#define IDC_EDIT5                       1025
#define IDC_EDIT_SQLID                  1025
#define IDC_EDIT6                       1026
#define IDC_EDIT_SQLIP                  1026
#define IDC_BUTTON_EXIT                 1027
#define IDC_BUTTON_SAVE                 1027
#define IDC_BUTTON2                     1028
#define IDC_BUTTON_ORGBTN               1028
#define IDC_EDIT_USERSELECTEDPASSWD2    1028
#define IDC_BUTTON_OPTION               1028
#define IDC_BUTTON_CUSTOMDX             1028
#define IDC_BUTTON_SQLCONFIG            1029
#define IDC_BUTTON3                     1030
#define IDC_BUTTON_THUMBBTN             1030
#define IDC_LIST_DXLIST                 1030
#define IDC_BUTTON_CUSTOM_DIAGNOSIS     1030
#define IDC_EDIT_HOSPITALID             1031
#define IDC_PROGRESS1                   1032
#define IDC_LIST_USERLIST               1032
#define IDC_PROGRESS_MAIN               1032
#define IDC_PROGRESS_PROGRESSBAR        1032
#define IDC_EDIT_FTPIP                  1033
#define IDC_EDIT_FTPID                  1034
#define IDC_LIST_CHOOSE_DX              1034
#define IDC_EDIT_FTPPASS                1035
#define IDC_EDIT_BACKUPSQLHOST          1035
#define IDC_PICTURE                     1036
#define IDC_EDIT_BACKUPSQLID            1036
#define IDC_EDIT_BACKUPSQLPASSWD        1037
#define IDC_TREE_REMOTE                 1038
#define IDC_EDIT_BACKUPSQLDBNAME        1038
#define IDC_BUTTON_PATHODX              1040
#define IDC_CHECK_SEARCH_ID             1042
#define IDC_CHECK_SEARCH_NAME           1043
#define IDC_EDIT_SERVERID               1043
#define IDC_CHECK_SEARCH_DX             1044
#define IDC_CHECK_SEARCH_ICD            1045
#define IDC_CHECK_SEARCH_C              1046
#define IDC_BUTTON_LOGINEXIT            1046
#define IDC_CHECK_INTEL_SELECT          1047
#define IDC_BUTTON_SETPRIDX             1048
#define IDC_CHECK_CHANGE_NAME_AUTO      1048
#define IDC_LIST_CUSTOMDX               1049
#define IDC_BUTTON_SUBMITTAG            1050
#define IDC_STATIC_CREDIT               1051
#define IDC_EDIT_COMMENTINPUT           1052
#define IDC_STATIC_CREDIT2              1052
#define IDC_STATIC_CREDIT3              1053
#define IDC_BUTTON_CREDIT               1054
#define IDC_LIST_COMMENTLIST            1056
#define IDC_BUTTON_UPDATE               1056
#define IDC_STATIC_UPDATE               1057
#define IDC_LIST_DX                     1058
#define IDC_EDIT_IDSTYLE                1059
#define IDC_LIST_COMMENT                1059
#define IDC_EDIT_USERSELECTED_NAME      1061
#define IDC_TAB1                        1063
#define IDC_TAB_OPTION                  1063
#define IDC_LIST1                       1065
#define IDC_LIST_PHOTO                  1065
#define IDC_LIST_STATUS                 1065
#define IDC_LIST_SELECTLIST             1065
#define IDC_STATIC_DX                   1066
#define IDC_BUTTON_REPORTG              1067
#define IDC_STATIC_DATE                 1067
#define IDC_STATIC_RIGHT                1069
#define IDC_STATIC_LEFT                 1070
#define IDC_STATIC_ZOOM                 1071
#define IDC_STATIC_PREV                 1072
#define IDC_LIST_DXFILE                 1073
#define IDC_STATIC_NEXT                 1073
#define IDC_PROGRESSBAR                 1074
#define IDC_LIST_DXACTIVEFILE           1074
#define IDC_STATIC_ROTATE               1074
#define IDC_BUTTON1                     1075
#define IDC_STATIC_ROTATE2              1075
#define IDC_BUTTON_OTHERDX              1076
#define IDC_BUTTON_SINGLE_CLIENT        1076
#define IDC_STATIC_CLOSED               1076
#define IDC_CHECK_SINGLE_CLIENT         1077
#define IDC_BUTTON_SINGLE               1078
#define IDC_BUTTON_MULTI                1079
#define IDC_BUTTON_RESETDB              1080
#define IDC_STATIC_LOGO                 1080
#define IDC_CHECK_SUBMITCHANGE          1081
#define IDC_STATIC_CAPTION_DELETE       1082
#define IDC_STATIC_F12                  1084
#define IDC_STATIC_VERSION              1085
#define IDC_LIST2                       1086
#define IDC_LIST_CHECKLIST              1086
#define IDC_DATETIMEPICKER_FROM         1087
#define IDC_DATETIMEPICKER_TO           1088
#define IDC_STATIC_HAN                  1089
#define IDC_STATIC_TIP                  1090
#define IDC_BUTTON_VIEWLOGO_EXIT        1091
#define IDC_EDIT_PICTUREFOLDER          1092
#define IDC_BUTTON_PIC                  1094
#define IDC_EDIT_DATE                   1103
#define IDC_STATIC_PTINFO               1104
#define IDC_STATIC_ID                   1105
#define IDC_STATIC_NAME                 1109
#define IDC_STATIC_SEX                  1110
#define IDC_STATIC_BIRTH                1111
#define IDC_CHECK_AUTOPATH              1113
#define ID_POPUP_TREE_COPY              32771
#define ID_POPUP_TREE_TOEXCELFILE       32772
#define ID_VIEW_BASIC                   32773
#define ID_VIEW_ADVANCED                32774
#define ID_ABOUT_ABOUT                  32775
#define ID_ABOUT_UPDATE                 32776
#define ID_PREFERENCE_PREFERENCE        32777
#define ID_POPUP_TREE_CREATE            32780
#define ID_POPUP_RENAME                 32781
#define ID_POPUP_LIST_COPY              32782
#define ID_POPUP_LIST_TOEXCELFILE       32783
#define ID_POPUP_LIST_DELETE            32784
#define ID_POPUP_TOPOWERPOINT           32785
#define ID_POPUP_DELETE                 32787
#define ID_POPUP_TOPOWERPOINT_LIST      32788
#define ID_POPUP_TOPOWERPOINT_TREE      32789
#define ID_POPUP_RENAME32791            32791
#define ID_POPUP_LIST_RENAME            32792
#define ID_POPUP_UPLOAD                 32793
#define ID_POPUP_TREE_UPLOAD            32794
#define ID_POPUP_UPLOAD32795            32795
#define ID_POPUP_LIST_UPLOAD            32796
#define ID_DIAGNOSIS_USERDIAGNOSIS      32797
#define ID_UPLOAD_UPLOADEX              32798
#define ID_POPUP_DISSELECTALL           32799
#define ID_TOOL_REPORT                  32800
#define ID_POPUP_REPORT                 32801
#define ID_POPUP_REPORT32802            32802
#define ID_POPUP_TREE_REPORT            32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
