#pragma once

enum ThreadType
{
	PICTURELOADING_THREAD
	,SQLBUILD_THREAD
	,SQLCHECK_THREAD
	,THUMBCHECK_THREAD
	,THUMBBUILD_THREAD
	,BUILDMETATAG_THREAD
	,LOAD_DXDB_THREAD
	,LOAD_DXDB_THREAD_WRAPPER
	,BROWSE_THREAD
	,COMMENT_THREAD
	,PROCESSIMAGE_THREAD
	,DXSEARCH_THREAD
	,IDLESIGNAL_THREAD
};
